const districts = [
  "Colombo",
  "Kandy",
  "Galle",
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Moneragala",
  "Mullativu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya"
];

const provinces = [
  "Central",
  "Northern",
  "North Central",
  "North Western",
  "Sabaragamuwa",
  "Southern",
  "Uva",
  "Western",
  "Eastern"
];

const distProv = [
  { district: "Colombo", province: "Western" },
  { district: "Kandy", province: "Central" },
  { district: "Galle", province: "Southern" },
  { district: "Ampara", province: "Eastern" },
  { district: "Anuradhapura", province: "North Central" },
  { district: "Badulla", province: "Uva" },
  { district: "Batticaloa", province: "Eastern" },
  { district: "Gampaha", province: "Western" },
  { district: "Hambantota", province: "Southern" },
  { district: "Jaffna", province: "Northern" },
  { district: "Kalutara", province: "Western" },
  { district: "Kegalle", province: "Sabaragamuwa" },
  { district: "Kilinochchi", province: "Northern" },
  { district: "Kurunegala", province: "North Western" },
  { district: "Mannar", province: "Northern" },
  { district: "Matale", province: "Central" },
  { district: "Matara", province: "Southern" },
  { district: "Moneragala", province: "Uva" },
  { district: "Mullativu", province: "Northern" },
  { district: "Nuwara Eliya", province: "Central" },
  { district: "Polonnaruwa", province: "North Central" },
  { district: "Puttalam", province: "North Western" },
  { district: "Ratnapura", province: "Sabaragamuwa" },
  { district: "Trincomalee", province: "Eastern" },
  { district: "Vavuniya", province: "Northern" }
];
